trigger:  # don't trigger automatically for now
- none



jobs:
- job: dependencies
  displayName: prepare gcpedia dependencies
  pool:
    vmImage: ubuntu-latest
  container: debian:11
  steps:
  - bash: |
      echo "list all ffmpeg dependencies"
      sudo apt-get update
      apt-cache rdepends ffmpeg
- job: build
  displayName: build gcpedia site code
  pool:
    vmImage: ubuntu-latest
  steps:
  - bash: |
      php --version
      composer --version
      git --version
      curl --version
      git submodule init && git submodule update --recursive --init
      cd extensions/OpenIDConnect && composer install --no-dev --no-interaction
      cd ../PluggableAuth && composer install --no-dev --no-interaction
      cd ../TimedMediaHandler && composer install --no-dev --no-interaction
      cd ../Widgets && composer install --no-dev --no-interaction
      mkdir -p /tmp/gcpedia_build/gcwiki && cd /tmp/gcpedia_build/gcwiki
      MEDIAWIKI_MAJOR_VERSION=1.40 && MEDIAWIKI_VERSION=1.40.2
      curl -fSL "https://releases.wikimedia.org/mediawiki/${MEDIAWIKI_MAJOR_VERSION}/mediawiki-${MEDIAWIKI_VERSION}.tar.gz" -o mediawiki.tar.gz
      curl -fSL "https://releases.wikimedia.org/mediawiki/${MEDIAWIKI_MAJOR_VERSION}/mediawiki-${MEDIAWIKI_VERSION}.tar.gz.sig" -o mediawiki.tar.gz.sig
      export GNUPGHOME="$(mktemp -d)"
      gpg --batch --keyserver keyserver.ubuntu.com --recv-keys \
      D7D6767D135A514BEB86E9BA75682B08E8A3FEC4 \
      441276E9CCD15F44F6D97D18C119E1A64D70938E \
      F7F780D82EBFB8A56556E7EE82403E59F9F8CD79 \
      1D98867E82982C8FE0ABC25F9B69B3109D3BB7B0
      gpg --batch --verify mediawiki.tar.gz.sig mediawiki.tar.gz
      tar -x --strip-components=1 -f mediawiki.tar.gz
      gpgconf --kill all
      rm -r "$GNUPGHOME" mediawiki.tar.gz.sig mediawiki.tar.gz
      cp -r $(Pipeline.Workspace)/s/* ./
      cp -r $(Pipeline.Workspace)/s/.azure ./
      mkdir deb
      mkdir deb/memcached
      wget http://http.us.debian.org/debian/pool/main/m/memcached/memcached_1.6.9+dfsg-1_amd64.deb -O deb/memcached/memcached_1.6.9+dfsg-1_amd64.deb
      wget http://http.us.debian.org/debian/pool/main/libe/libevent/libevent-2.1-7_2.1.12-stable-1_amd64.deb -O deb/memcached/libevent-2.1-7_2.1.12-stable-1_amd64.deb
      mkdir deb/imagemagick
      wget http://security.debian.org/debian-security/pool/updates/main/i/imagemagick/imagemagick_6.9.11.60+dfsg-1.3+deb11u3_amd64.deb -O deb/imagemagick/imagemagick_6.9.11.60+dfsg-1.3+deb11u3_amd64.deb
      wget http://security.debian.org/debian-security/pool/updates/main/i/imagemagick/imagemagick-6.q16_6.9.11.60+dfsg-1.3+deb11u3_amd64.deb -O deb/imagemagick/imagemagick-6.q16_6.9.11.60+dfsg-1.3+deb11u3_amd64.deb
      wget http://http.us.debian.org/debian/pool/main/h/hicolor-icon-theme/hicolor-icon-theme_0.17-2_all.deb -O deb/imagemagick/hicolor-icon-theme_0.17-2_all.deb
      mkdir deb/icu
      wget http://http.us.debian.org/debian/pool/main/i/icu/libicu-dev_67.1-7_amd64.deb -O deb/icu/libicu-dev_67.1-7_amd64.deb
      mkdir deb/libonig
      wget http://http.us.debian.org/debian/pool/main/libo/libonig/libonig-dev_6.9.6-1.1_amd64.deb -O deb/libonig/libonig-dev_6.9.6-1.1_amd64.deb
      mkdir deb/htmldoc
      wget http://http.us.debian.org/debian/pool/main/h/htmldoc/htmldoc_1.9.11-4+deb11u3_amd64.deb -O deb/htmldoc/htmldoc_1.9.11-4+deb11u3_amd64.deb
      wget http://http.us.debian.org/debian/pool/main/h/htmldoc/htmldoc-common_1.9.11-4+deb11u3_all.deb  -O deb/htmldoc/htmldoc-common_1.9.11-4+deb11u3_all.deb
      wget http://http.us.debian.org/debian/pool/main/f/fltk1.3/libfltk-images1.3_1.3.5-3_amd64.deb  -O deb/htmldoc/libfltk-images1.3_1.3.5-3_amd64.deb
      wget http://http.us.debian.org/debian/pool/main/f/fltk1.3/libfltk1.3_1.3.5-3_amd64.deb -O deb/htmldoc/libfltk1.3_1.3.5-3_amd64.deb
      wget http://http.us.debian.org/debian/pool/main/libx/libxcursor/libxcursor1_1.2.0-2_amd64.deb  -O deb/htmldoc/libxcursor1_1.2.0-2_amd64.deb
      wget http://http.us.debian.org/debian/pool/main/libx/libxfixes/libxfixes3_5.0.3-2_amd64.deb -O deb/htmldoc/libxfixes3_5.0.3-2_amd64.deb
      wget http://http.us.debian.org/debian/pool/main/x/xft/libxft2_2.3.2-2_amd64.deb -O deb/htmldoc/libxft2_2.3.2-2_amd64.deb
      wget http://http.us.debian.org/debian/pool/main/libx/libxinerama/libxinerama1_1.1.4-2_amd64.deb -O deb/htmldoc/libxinerama1_1.1.4-2_amd64.deb
      ls -la
    displayName: prepare gcpedia code build environment

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '/tmp/gcpedia_build/gcwiki'
      includeRootFolder: true
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    displayName: 'Upload package'
    artifact: drop

- job: deploy
  displayName: deploy gcpedia site code
  pool: $(deployPool)
  dependsOn: build
  condition: succeeded()
  steps:
  - download: current
    artifact: drop
  - task: AzureWebApp@1
    displayName: 'Deploy Azure Web App gcpedia code'
    inputs:
      azureSubscription: $(azSubServiceConnection)
      appName: $(appName)
      package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
