trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Sync azure repo
    B64_PAT=$(echo -n ":$PAT" | base64)
    git clone --bare https://$(System.AccessToken)@dev.azure.com/tbs-sct/GCtools/_git/$REPO_NAME Sync_directory
    cd Sync_directory
    git remote add --mirror=fetch upstream https://github.com/gctools-outilsgc/$REPO_NAME
    git fetch upstream --tags
    git push origin --all
  env:
    PAT: $(PAT)
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    REPO_NAME: "gcpedia"
  displayName: 'Sync repo'
