version: '2'
services:
  # ###########################################################################
  # The GCpedia container.  Will be accessible at http://wiki.local
  # ###########################################################################
  gcpedia:
    container_name: gcpedia
    build: .
    ports:
      - 80:80
    volumes:
      - ./images:/var/www/html/images
      - ./compiled_templates:/var/www/html/extensions/Widgets/compiled_templates/
    links:
      - gcpedia-db
    depends_on:
      - gcpedia-db
    environment:
      - DOCKER=1
      - DBTYPE=mysql
      - DBHOST=gcpedia-db
      - DBNAME=wiki
      - DBUSER=wiki
      - DBPASS=gcpedia
      - WIKI_HOST=wiki.local
      - WIKI_PROTOCOL=http
      - WIKI_PORT=
      - INIT=wiki
      - DBSSL=0
      - OPENID=
      - SITE=gcpedia
      - WIKI_DEBUG=true
#      - OAUTH=true
#      - USESAML=false

  # ###########################################################################
  # Database container for gcpedia, accessible from by the gcpedia container 
  # using the network host "gcpedia-db".
  # ###########################################################################
  gcpedia-db:
    container_name: gcpedia-db
    image: mariadb:10.3
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gcpedia
      - MYSQL_DATABASE=wiki
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=gcpedia
