version: '3.3'
services:
  # ###########################################################################
  # Jenkins container. 
  # ###########################################################################
  jenkins:
    image: jenkins/jenkins:alpine
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
    networks:
      - jenkins-workers
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 1000M
        reservations:
          cpus: '0.05'
          memory: 50M

  # ###########################################################################
  # Jenkins docker worker node.
  # requires Self-Organizing Swarm Plug-in Modules plugin
  # it will connect to jenkins once it's set up and the plugin installed
  # assuming you use the same uername + password as below
  # ###########################################################################
  jenkins_worker:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - "COMMAND_OPTIONS=-master http://jenkins:8080 -username admin -password admin -labels 'dockerDev' -executors 5"
    networks:
      - jenkins-workers
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.001'
          memory: 20M
  
  # ###########################################################################
  # Local image registry container. 
  # ###########################################################################
  registry:
    image: registry
    networks:
      - jenkins-workers
    deploy:
      replicas: 1

volumes:
  jenkins_home:

networks:
  jenkins-workers:
    driver: overlay
    internal: true