version: '2'
services:
  # ###########################################################################
  # The GCpedia container.  Will be accessible at http://wiki.gccollab.dev
  # ###########################################################################
  gcpedia:
  #  change 
  #  build: .
    image: phanoix/gcpedia
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./skins:/var/www/html/docker_gcpedia/skins
      - ./extensions:/var/www/html/docker_gcpedia/extensions
      - ./images:/var/www/html/docker_gcpedia/images
      - /var/www/html/docker_gcpedia/vendor
      - /var/www/html/docker_gcpedia/docker
      # submodules - should not be modified anyways
      - /var/www/html/docker_gcpedia/skins/CologneBlue
      - /var/www/html/docker_gcpedia/skins/Modern
      - /var/www/html/docker_gcpedia/skins/MonoBook
      - /var/www/html/docker_gcpedia/skins/MinervaNeue
      - /var/www/html/docker_gcpedia/extensions/ConfirmEdit
      - /var/www/html/docker_gcpedia/extensions/Gadgets
      - /var/www/html/docker_gcpedia/extensions/Nuke
      - /var/www/html/docker_gcpedia/extensions/ParserFunctions
      - /var/www/html/docker_gcpedia/extensions/Renameuser
      - /var/www/html/docker_gcpedia/extensions/WikiEditor
      - /var/www/html/docker_gcpedia/extensions/Cite
      - /var/www/html/docker_gcpedia/extensions/ImageMap
      - /var/www/html/docker_gcpedia/extensions/InputBox
      - /var/www/html/docker_gcpedia/extensions/Interwiki
      - /var/www/html/docker_gcpedia/extensions/LocalisationUpdate
      - /var/www/html/docker_gcpedia/extensions/Poem
      - /var/www/html/docker_gcpedia/extensions/SyntaxHighlight_GeSHi
      - /var/www/html/docker_gcpedia/extensions/TitleBlacklist
      - /var/www/html/docker_gcpedia/extensions/CiteThisPage
      - /var/www/html/docker_gcpedia/extensions/PdfHandler
      - /var/www/html/docker_gcpedia/extensions/SpamBlacklist
      - /var/www/html/docker_gcpedia/extensions/ElectronPdfService
      - /var/www/html/docker_gcpedia/extensions/CategoryTree
      - /var/www/html/docker_gcpedia/extensions/EditUser
      - /var/www/html/docker_gcpedia/extensions/LookupUser
      - /var/www/html/docker_gcpedia/extensions/ReplaceText
      - /var/www/html/docker_gcpedia/extensions/UserMerge
      - /var/www/html/docker_gcpedia/extensions/CharInsert
      - /var/www/html/docker_gcpedia/extensions/CSS
      - /var/www/html/docker_gcpedia/extensions/intersection
      - /var/www/html/docker_gcpedia/extensions/RSS
      - /var/www/html/docker_gcpedia/extensions/UniversalLanguageSelector
      - /var/www/html/docker_gcpedia/extensions/MobileFrontend
      - /var/www/html/docker_gcpedia/extensions/VisualEditor
      - /var/www/html/docker_gcpedia/extensions/IframePage
      - /var/www/html/docker_gcpedia/extensions/googleAnalytics
      - /var/www/html/docker_gcpedia/extensions/DeletePagesForGood
      - /var/www/html/docker_gcpedia/extensions/Lingo
    links:
      - gcpedia-db
    depends_on:
      - gcpedia-db
    environment:
      - DOCKER=1
      - DBHOST=gcpedia-db
      - HOST=wiki.local
      - PORT=
      - OPENID=
#      - OAUTH=true
#      - USESAML=false

  # ###########################################################################
  # The parsoid container for the VisualEditor.
  # Will be available to gcpedia at parsoid:8142
  # ###########################################################################
  parsoid:
    #build:
    #  context: .
    #  dockerfile: Dockerfile.parsoid
    image: phanoix/parsoid:latest
    ports:
      - 8142:8000

  # ###########################################################################
  # The Electron render service container for the ElectronPdfService Extension.
  # Will be available to gcpedia at elec-render:3000
  # ###########################################################################
 # elec-render:
 #   image: msokk/electron-render-service
 #   ports:
 #     - 3000:3000

  # ###########################################################################
  # Database container for gcpedia, accessible from by the gcpedia container 
  # using the network host "gcpedia-db".
  # ###########################################################################
  gcpedia-db:
    image: library/mariadb:10.3
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gcpedia
      - MYSQL_DATABASE=wiki
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=gcpedia
