#!/bin/sh
### BEGIN INIT INFO
# Provides:          mwlib
# Required-Start:    $local_fs $network $remote_fs $syslog
# Required-Stop:     $local_fs $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Web service for enerating pdf versions of wikitext pages
# Description:       Generates pdf versions of wikitext pages
### END INIT INFO

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="mwlib HTTP service"
NAME=mwlib
CACHE_PATH=/sites/mwlib
LOG_PATH=/sites/mwlib/logs
SCRIPTNAME=/etc/init.d/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	start-stop-daemon -c mwlib:mwlib  --name nserve --background --start --exec /bin/sh -- -c "/usr/bin/python /usr/local/bin/nserve   > $LOG_PATH/nserve.log 2>&1"
	start-stop-daemon -c mwlib:mwlib  --name mw-qserve --background --start --exec /bin/sh -- -c "/usr/bin/python  /usr/local/bin/mw-qserve > $LOG_PATH/mw-qserve.log 2>&1"
	start-stop-daemon -c mwlib:mwlib  --name nslave --background --start --exec /bin/sh -- -c "/usr/bin/python /usr/local/bin/nslave --cachedir $CACHE_PATH/mwcache > $LOG_PATH/nslave.log 2>&1"

	return 0
}


#
# Function that stops the daemon/service
#
do_stop()
{
    start-stop-daemon --user mwlib --stop

	return 0
}


case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
		# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >>&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}"
	exit 3
	;;
esac
