apiVersion: v1
kind: Service
metadata:
  name: gcpedia
  namespace: gctools-test
  annotations:
    VIRTUAL_HOST: "gcpedia.gctools.nrc.ca"
    VIRTUAL_PORT: "80"
spec:
  ports:
    - protocol: TCP
      port: 80
  selector: 
    app: gcpedia
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcpedia-deployment
  namespace: gctools-test
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: gcpedia
    spec:
      containers:
      - name: gcpedia
        image: localhost:5000/gctools-outilsgc/gcpedia:latest
        ports:
        - containerPort: 80
        env:
        - name: "DOCKER"
          value: "1"
        - name: "DBHOST"
          value: "gcpedia-db.gctools-test"
        - name: "HOST"
          value: "gcpedia.gctools.nrc.ca"
        - name: "PORT"
          value: "80"
        volumeMounts:
        - mountPath: /var/www/html/image
          name: gcpedia-data-volume
        - mountPath: /var/www/html/LocalSettings.php
          subPath: LocalSettings.php
          name: gcpedia-settings
      - name: parsoid
        image: localhost:5000/gctools-outilsgc/parsoid:latest
        ports:
        - containerPort: 8142
      - name: render
        image: localhost:5000/gctools-outilsgc/electron-render-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: "RENDERER_ACCESS_KEY"
          value: "secret"
        - name: HOSTNAME
          value: ""
        - name: "CONCURRENCY"
          value: "1"
        - name: "TIMEOUT"
          value: "30"
        - name: "WINDOW_WIDTH"
          value: "1024"
        - name: "WINDOW_HEIGHT"
          value: "768"
        - name: "PORT"
          value: "3000"
      volumes:
      - name: gcpedia-data-volume
        persistentVolumeClaim:
          claimName: gcpedia-data-volume-claim
      - name: gcpedia-settings
        configMap:
          name: gcpedia-config
---
apiVersion: v1
kind: Service
metadata:
  name: gcpedia-db
  namespace: gctools-test
spec:
  clusterIP: None
  ports: 
    - protocol: TCP
      port: 3306
  selector:
    app: gcpedia-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcpedia-db-deployment
  namespace: gctools-test
spec:
  replicas: 1 # tells deployment to run 1 pod matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: gcpedia-db
    spec:
      containers:
      - name: mysql
        image: localhost:5000/mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "gcpedia"
        - name: "MYSQL_DATABASE"
          value: "wiki"
        - name: "MYSQL_USER"
          value: "wiki"
        - name: "MYSQL_PASSWORD"
          value: "gcpedia"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: gcpedia-db-volume
      volumes:
      - name: gcpedia-db-volume
        persistentVolumeClaim:
          claimName: gcpedia-db-volume-claim