trigger:  # triggered manually when needed
- none


jobs:
- job: import
  displayName: import sql dump
  pool: $(deployPool)
  steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: $(azSubServiceConnection)
      KeyVaultName: $(KV_NAME)
      SecretsFilter: $(KV_SECRETS_LIST)
      RunAsPreJob: false

  - bash: |
    gunzip -c $(DUMP_FILE_NAME) | mysql -h $(DB_HOST) -u $(DB_USER) -p $(DB_PASS) $(DB_NAME)
