trigger:  # triggered manually when needed
- none


jobs:
- job: import
  displayName: import sql dump
  pool: $(deployPool)
  steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: $(azSubServiceConnection)
      KeyVaultName: $(KV_NAME)
      SecretsFilter: $(KV_SECRETS_LIST)
      RunAsPreJob: false

  - task: AzureCLI@2
    displayName: download and import
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: bash
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage blob download --account-name $(STORAGE_ACCOUNT) --container-name $(STORAGE_CONTAINER) --file "$(DUMP_FILE_NAME)" --name "$(DUMP_BLOB_NAME)"
        gunzip -c $(DUMP_FILE_NAME) | mysql -h $(DB_HOST) -u $(DB_USER) -p $(DB_PASS) $(DB_NAME)
