name: "Haibun e2e tests"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  e2e_test_and_publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout main branch
      - uses: actions/checkout@v4
        with:
          repository: gctools-outilsgc/gcpedia
          ref: main

      # Set up GitHub Actions bot identity
      - uses: fregante/setup-git-user@v2

      - name: Set up GitHub Actions bot identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "vid_github@zooid.org"

      # Build and run Docker container
      - name: Build gcpedia docker-compose
        run: docker-compose build

      - name: Make images directory
        run: mkdir images

      - name: Set images permissions
        run: chmod 777 images/

      - name: Start gcpedia docker-compose
        run: docker-compose up -d

      - name: See the logs
        run: docker-compose logs

      - name: Wait for it to start
        continue-on-error: true
        run: |
          npx -y wait-on -t 45s tcp:`./haibun/gcpedia-docker-address.sh`:80

      - name: See the logs if wait failed
        if: steps.wait-for-it.outputs.success == 'false'
        run: docker-compose logs

      - name: Fail the job if wait failed
        if: steps.wait-for-it.outputs.success == 'false'
        run: exit 1

      # Fetch and switch to gh-pages branch
      - name: Fetch and switch to gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git switch gh-pages

      # Reset gh-pages to main, except for haibun/reviews
      - name: Reset gh-pages to main
        run: |
          git reset --hard origin/main
          git checkout origin/gh-pages -- haibun/reviews

      # Install haibun dependencies
      - name: Install haibun dependencies
        run: |
          cd haibun
          npm ci
          npx playwright install-deps
          npx playwright install

      # Run e2e tests
      - name: Run e2e tests
        continue-on-error: true
        run: |
          cd haibun
          npm run docker-test

      # Run publish
      - name: Run publish
        run: |
          cd haibun
          npm run publish

      # Add and commit changes
      - name: Add and commit changes
        run: |
          git add ./haibun/reviews
          git commit -m "update e2e test reviews"

      # Push changes to gh-pages
      - name: Push changes to gh-pages
        run: |
          git push origin gh-pages
